language: go

go:
  - 1.15.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - go test -gcflags=all=-l -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
