Server:
  RunMode: debug
  HttpPort: 8001
  RPCPort: 8002
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: log
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: upload/files
  UploadServerUrl: http://localhost:8001/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 60
  HashSalt: EntryTask2021
Database:
  DBType: mysql
  Username: root
  Password: 9596abcd@@@
  Host: localhost:3306
  DBName: entry_task_v2_db
  Charset: utf8mb4
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
Redis:
  Host: localhost:6379
  DBIndex: 0
